# Generated by Django 5.0.6 on 2024-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tremors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='tremors',
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(default='120/80', max_length=50),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.CharField(default='90', max_length=10),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='o2_saturation',
            field=models.CharField(blank=True, default='90', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='respiration_rate',
            field=models.CharField(default='12', max_length=10),
        ),
    ]
