# Generated by Django 5.0.6 on 2024-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vitals_tremors_alter_vitals_blood_pressure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='o2_saturation',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='respiration_rate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
