# Generated by Django 5.0.6 on 2024-08-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_departments_alter_vitals_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='tremors',
            options={'verbose_name_plural': 'Tremors'},
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name_plural': 'Vitals'},
        ),
    ]
