# Generated by Django 5.0.6 on 2024-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='national_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
