# Generated by Django 5.0.6 on 2024-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_dob_remove_customuser_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
