# Generated by Django 5.0.6 on 2024-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_delete_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
