# Generated by Django 5.0.6 on 2024-08-29 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email_name', models.CharField(blank=True, default='Bengomall Team', max_length=255, null=True)),
                ('from_email', models.EmailField(default='bengomallKE@gmail.com', max_length=100)),
                ('email_password', models.CharField(default='obqvwmnpioaclyhj', max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=50)),
                ('email_port', models.CharField(default=587, max_length=5)),
                ('use_tls', models.BooleanField(default=True)),
                ('fail_silently', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
